##
#docker-compose.yml

# Usage:
#   export DOCKER_IMAGE_TAG=$(git rev-parse --short HEAD)
#   docker-compose -f docker-compose.yml -f docker-compose.gcp.yml
##

version: "3.2"
services:
  flask:
    build: .
    restart: always
    ports:
      - 80:5000
    stdin_open: true
    tty: true
    command: ['flask','run']
    volumes:
      - .:/home/myuser